gui:
  splitDiff: "always"
  scrollPastBottom: true
  showIcons: true
  authorColors:
    "Peter Cardenas": "yellow"
    "PeterPCardenas": "yellow"
    "*": "white"
  branchColors:
    "pcardenas": "yellow"
    "master": "red"
  theme:
    cherryPickedCommitBgColor:
      - "#A39B8F"
keybinding:
  commits:
    moveDownCommit: '<c-n>' # move commit down one
    moveUpCommit: '<c-p>' # move commit up one
# TODO: Add Ctrl-Down and Ctrl-Up to move commits around (workaround since ctrl-k and ctrl-j are mapped in nvim)
# TODO: Skip confirmation of opening up editor when renaming commits

