gui:
  splitDiff: "always"
  scrollPastBottom: true
  showIcons: true
  authorColors:
    "Peter Cardenas": "yellow"
    "PeterPCardenas": "yellow"
    "*": "white"
  branchColors:
    "pcardenas": "yellow"
    "master": "red"
  theme:
    selectedLineBgColor: "#A39B8F"
    selectedRangeBgColor: "#A39B8F"
