gui:
  # TODO: there is no fuzzy filtering for files
  filterMode: 'fuzzy'
  skipRewordInEditorWarning: true
  splitDiff: "always"
  scrollPastBottom: true
  animateExplosion: true
  authorColors:
    "Peter Cardenas": "yellow"
    "PeterCardenas": "yellow"
    "PeterPCardenas": "yellow"
    "peter-cardenas-ai": "yellow"
    "*": "white"
  nerdFontsVersion: '3'
  branchColors:
    "pcardenas": "yellow"
    "master": "#9ece6a"
    "main": "#9ece6a"
  theme:
    selectedLineBgColor:
      - "#374261"
    activeBorderColor:
      - "#ff9e64"
      - "bold"
    inactiveBorderColor:
      - "#29a4bd"
    searchingActiveBorderColor:
      - "#ff9e64"
      - "bold"
    optionsTextColor:
      - "#7aa2f7"
    cherryPickedCommitFgColor:
      - "#7aa2f7"
    cherryPickedCommitBgColor:
      - "#3901a0"
    markedBaseCommitFgColor:
      - "#7aa2f7"
    markedBaseCommitBgColor:
      - "#e0af68"
    unstagedChangesColor:
      - "#db4b4b"
    defaultFgColor:
      - "#c0caf5"
keybinding:
  # TODO: Push/pull branches that are not checked out
  files:
    commitChanges: 'C'
    commitChangesWithEditor: 'c'
  commits:
    moveDownCommit: '<c-n>'
    moveUpCommit: '<c-p>'
    renameCommit: 'R'
    renameCommitWithEditor: 'r'
git:
  parseEmoji: true
  overrideGpg: true
  # TODO: set --verbose when running commit editor
  # TODO: use branchPrefix but specific to repos
  # TODO: commitPrefix but specific to repos
  paging:
    colorArg: always
    pager: delta --dark --paging=never
# TODO: does not chnage bottom prompt when entering patch commit message, or use editor
# TODO: checkout freezes the gui
notARepository: 'skip'
promptToReturnFromSubprocess: false
disableStartupPopups: true
quitOnTopLevelReturn: true
# TODO: rebase continue freezes the gui
# TODO: discard changes freezes the gui
os:
  editPreset: 'nvim-remote'
  edit: 'lazygit_nvim {{filename}}'
  editAtLine: 'lazygit_nvim {{filename}} {{line}}'
  openDirInEditor: 'lazygit_nvim {{dir}}'
  copyToClipboardCmd: osc52_copy {{text}}
