gui:
  skipRewordInEditorWarning: true
  splitDiff: "always"
  scrollPastBottom: true
  animateExplosion: true
  authorColors:
    "Peter Cardenas": "yellow"
    "PeterPCardenas": "yellow"
    "*": "white"
  nerdFontsVersion: '3'
  branchColors:
    "pcardenas": "yellow"
    "master": "#9ece6a"
    "main": "#9ece6a"
  theme:
    selectedLineBgColor:
      - "#374261"
    activeBorderColor:
      - "#ff9e64"
      - "bold"
    inactiveBorderColor:
      - "#29a4bd"
    searchingActiveBorderColor:
      - "#ff9e64"
      - "bold"
    optionsTextColor:
      - "#7aa2f7"
    cherryPickedCommitFgColor:
      - "#7aa2f7"
    cherryPickedCommitBgColor:
      - "#bb9af7"
    markedBaseCommitFgColor:
      - "#7aa2f7"
    markedBaseCommitBgColor:
      - "#e0af68"
    unstagedChangesColor:
      - "#db4b4b"
    defaultFgColor:
      - "#c0caf5"
keybinding:
  files:
    commitChanges: 'C'
    commitChangesWithEditor: 'c'
  commits:
    moveDownCommit: '<c-n>'
    moveUpCommit: '<c-p>'
    renameCommit: 'R'
    renameCommitWithEditor: 'r'
git:
  parseEmoji: true
  overrideGpg: true
  paging:
    colorArg: always
    pager: delta --dark --paging=never
notARepository: 'skip'
promptToReturnFromSubprocess: false
disableStartupPopups: true
quitOnTopLevelReturn: true
os:
  editPreset: 'nvim-remote'
  edit: '[ -z "$NVIM" ] && (nvim -- {{filename}}) || (nvim --server "$NVIM" --remote-send "<C-\\><C-n>:e {{filename}}<CR>")'
  editAtLine: '[ -z "$NVIM" ] && (nvim +{{line}} -- {{filename}}) || (nvim --server "$NVIM" --remote-send "<C-\\><C-n>:e {{filename}}<CR>:{{line}}<CR>")'
  openDirInEditor: '[ -z "$NVIM" ] && (nvim -- {{dir}}) || (nvim --server "$NVIM" --remote-send "<C-\\><C-n>:e {{dir}}<CR>")'
  copyToClipboardCmd: osc52_copy {{text}}
