gui:
  skipRewordInEditorWarning: true
  splitDiff: "always"
  scrollPastBottom: true
  animateExplosion: true
  authorColors:
    "Peter Cardenas": "yellow"
    "PeterPCardenas": "yellow"
    "*": "white"
  nerdFontsVersion: '3'
  branchColors:
    "pcardenas": "yellow"
    "master": "red"
    "main": "red"
  theme:
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
    cherryPickedCommitBgColor:
      - "#A39B8F"
keybinding:
  files:
    commitChanges: 'C'
    commitChangesWithEditor: 'c'
  commits:
    moveDownCommit: '<c-n>'
    moveUpCommit: '<c-p>'
    renameCommit: 'R'
    renameCommitWithEditor: 'r'
git:
  parseEmoji: true
notARepository: 'skip'
promptToReturnFromSubprocess: false
disableStartupPopups: true
quitOnTopLevelReturn: true
os:
  editPreset: 'nvim'
