gui:
  filterMode: 'fuzzy'
  skipRewordInEditorWarning: true
  splitDiff: "always"
  scrollPastBottom: true
  animateExplosion: true
  authorColors:
    "Peter Cardenas": "yellow"
    "PeterCardenas": "yellow"
    "PeterPCardenas": "yellow"
    "peter-cardenas-ai": "yellow"
    "*": "white"
  nerdFontsVersion: '3'
  branchColors:
    "pcardenas": "yellow"
    "master": "#9ece6a"
    "main": "#9ece6a"
  theme:
    selectedLineBgColor:
      - "#374261"
    activeBorderColor:
      - "#ff9e64"
      - "bold"
    inactiveBorderColor:
      - "#29a4bd"
    searchingActiveBorderColor:
      - "#ff9e64"
      - "bold"
    optionsTextColor:
      - "#7aa2f7"
    cherryPickedCommitFgColor:
      - "#7aa2f7"
    cherryPickedCommitBgColor:
      - "#bb9af7"
    markedBaseCommitFgColor:
      - "#7aa2f7"
    markedBaseCommitBgColor:
      - "#e0af68"
    unstagedChangesColor:
      - "#db4b4b"
    defaultFgColor:
      - "#c0caf5"
keybinding:
  files:
    commitChanges: 'C'
    commitChangesWithEditor: 'c'
  commits:
    moveDownCommit: '<c-n>'
    moveUpCommit: '<c-p>'
    renameCommit: 'R'
    renameCommitWithEditor: 'r'
git:
  parseEmoji: true
  overrideGpg: true
  paging:
    colorArg: always
    pager: delta --dark --paging=never
notARepository: 'skip'
promptToReturnFromSubprocess: false
disableStartupPopups: true
quitOnTopLevelReturn: true
os:
  editPreset: 'nvim-remote'
  # TODO: Directly calling nvim or any other editor doesn't work on MacOS
  edit: '[ -z "$NVIM" ] && (nvim -- {{filename}}) || (nvim --server "$NVIM" --remote-expr "execute(\"lua vim.cmd([[e {{filename}}]])\")")'
  editAtLine: '[ -z "$NVIM" ] && (nvim +{{line}} -- {{filename}}) || (nvim --server "$NVIM" --remote-expr "execute(\"lua vim.cmd([[e +{{line}} {{filename}}]])\")")'
  openDirInEditor: '[ -z "$NVIM" ] && (nvim -- {{dir}}) || (nvim --server "$NVIM" --remote-expr "execute(\"lua vim.cmd([[e {{dir}}]])\")")'
  copyToClipboardCmd: osc52_copy {{text}}
