prSections:
  - title: My Pull Requests
    filters: is:open author:@me
  - title: Needs My Review
    filters: is:open user-review-requested:@me   
issuesSections:
  - title: Mentioned Issues
    filters: mentions:@me
  - title: 1.42 P1s
    filters: is:open assignee:@me milestone:1.42 label:P1
  - title: 1.42 P2s
    filters: is:open assignee:@me milestone:1.42 label:P2
  - title: 1.41 P1s
    filters: is:open assignee:@me milestone:1.41 label:P1
  - title: 1.41 P2s
    filters: is:open assignee:@me milestone:1.41 label:P2
  - title: 1.40 P1s
    filters: is:open assignee:@me milestone:1.40 label:P1
