prSections:
  - title: My Pull Requests
    filters: is:open author:@me
  - title: Needs My Review
    filters: is:open user-review-requested:@me   
issuesSections:
  - title: Mentioned Issues
    filters: mentions:@me
  - title: Config
    filters: is:open repo:PeterCardenas/dotfiles
defaults:
  preview:
    open: false
    width: 1000
