complete -c claude -s d -l debug -d "Enable debug mode"
complete -c claude -l verbose -d "Override verbose mode setting from config"
complete -c claude -s p -l print -d "Print response and exit (useful for pipes)"
complete -c claude -l output-format -d "Output format (text, json, stream-json)" -xa "text json stream-json"
complete -c claude -l input-format -d "Input format (text, stream-json)" -xa "text stream-json"
complete -c claude -l mcp-debug -d "Enable MCP debug mode"
complete -c claude -l dangerously-skip-permissions -d "Bypass all permission checks"
complete -c claude -l allowedtools -d "Comma or space-separated list of tool names to allow"
complete -c claude -l disallowedtools -d "Comma or space-separated list of tool names to deny"
complete -c claude -l mcp-config -d "Load MCP servers from a JSON file or string"
complete -c claude -s c -l continue -d "Continue the most recent conversation"
complete -c claude -s r -l resume -d "Resume a conversation" -xa "(__claude_list_sessions)"
complete -c claude -l model -d "Model for the initial context" -xa "sonnet opus claude-sonnet-4-20250514"
complete -c claude -l fallback-model -d "Enable automatic fallback to specified model"
complete -c claude -l add-dir -d "Additional directories to allow tool access to"
complete -c claude -l ide -d "Automatically connect to IDE on startup"
complete -c claude -s v -l version -d "Output the version number"
complete -c claude -s h -l help -d "Display help for command"
