command_timeout = 2000

[directory]
truncate_to_repo = false

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "

[cmd_duration]
format = "[$duration]($style) "

[zig]
symbol = " "
format = "[$symbol($version)]($style) "

[python]
format = "[${symbol}${pyenv_prefix}(${version} )(\\($virtualenv\\) )]($style) "

[rust]
format = "[$symbol($version)]($style) "

[nodejs]
format = "[$symbol($version)]($style) "

[lua]
format = "[$symbol$version]($style) "

[golang]
format = "[$symbol]($style) "

[c]
format = "[$symbol$version]($style) "

[cmake]
format = "[$symbol$version]($style) "

[package]
format = "[$symbol$version]($style) "

[container]
symbol = "📦"
format = "[$symbol]($style) "

[username]
disabled = true

[hostname]
disabled = true

[gcloud]
disabled = true

[aws]
disabled = true
