command_timeout = 1000

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "

[cmd_duration]
format = "[$duration]($style) "

[python]
format = "[$symbol]($style)"

[nodejs]
format = "[$symbol($version)]($style) "

[lua]
format = "[$symbol$version]($style) "

[golang]
format = "[$symbol]($style)"

[c]
format = "[$symbol$version]($style) "

[cmake]
format = "[$symbol$version]($style) "

[package]
format = "[$symbol$version]($style) "

[container]
symbol = "📦"
format = "[$symbol]($style) "

[username]
disabled = true

[hostname]
disabled = true
