"$schema" = 'https://starship.rs/config-schema.json'
command_timeout = 2000
add_newline = false
format = """
$git_branch\
$git_commit\
$git_state\
$git_metrics"""

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
