"$schema" = 'https://starship.rs/config-schema.json'
command_timeout = 2000
add_newline = false
format = """$cmd_duration
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$gleam\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$nats\
$direnv\
$env_var\
$crystal\
$custom\
$sudo\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$character"""

[directory]
truncate_to_repo = false

[cmd_duration]
format = "[$duration]($style) "

[zig]
symbol = " "
format = "[$symbol($version)]($style) "

[python]
symbol = "🐍"
format = "[${symbol}${pyenv_prefix}(${version} )(\\($virtualenv\\) )]($style) "

[rust]
format = "[$symbol($version)]($style) "

[nodejs]
format = "[$symbol($version)]($style) "

[lua]
format = "[$symbol$version]($style) "

[golang]
symbol = "🐹"
format = "[$symbol$version]($style) "

[c]
format = "[$symbol$version]($style) "

[cmake]
format = "[$symbol$version]($style) "

[swift]
symbol = "󰛥 "
format = "[$symbol($version )]($style)"

[package]
format = "[$symbol$version]($style) "

[container]
symbol = "📦"
format = "[$symbol]($style) "

[username]
disabled = true

[hostname]
disabled = true

[gcloud]
disabled = true

[aws]
disabled = true
