"$schema" = 'https://starship.rs/config-schema.json'
command_timeout = 2000
add_newline = false
format = """$cmd_duration
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory"""

[directory]
truncate_to_repo = false

[cmd_duration]
format = "[$duration]($style) "

[username]
disabled = true

[hostname]
disabled = true
